Fixed AttributeError: 'SonicCli' object has no attribute 'dut' in test_wjh
Changes related to cli_obj which were done by me day ago introduced issue AttributeError: 'SonicCli' object has no attribute 'dut' which is fixed now

Change-Id: I64d65b0ce7fbf4f30ffd174c77130dd786be3a68