Fix test failure in test_cont_link_flap.py (#8128)
Fixes test failure in test_cont_link_flap.py caused by #7968

What is the motivation for this PR?
Test failed with error:
File "/azp/_work/6/s/tests/platform_tests/link_flap/test_cont_link_flap.py", line 145, in test_cont_link_flap
incr_redis_memory = float(end_time_redis_memory) - float(start_time_redis_memory)
ValueError: could not convert string to float: '\1'

How did you do it?
Correct reg express.

How did you verify/test it?
Manually run test case: test_cont_link_flap.py