Update the regexp for getting supported fec modes
The output when a invalid fec mode is set by the sonic cli has been changed by PR:https://github.com/sonic-net/sonic-utilities/pull/2223, need to update the regexp in ngts/cli_wrappers/sonic/sonic_interface_clis.py to match the new output.

Previous:
    admin@r-alligator-04:~$ sudo config interface fec Ethernet0 1111
    Usage: config interface fec [OPTIONS] <interface_name> <interface_fec>
    Try "config interface fec -h" for help.

    Error: 'fec not in ['rs', 'fc', 'none']!

Now:
admin@r-bulldog-02:~$ sudo config interface fec Ethernet0 1111
fec 1111 is not in ['fc', 'none', 'rs']

Change-Id: Ic4ee140a511573d3496a8a6adece709482671234