[Python3 migration]Fix test failure in test_vlan_ping.py (#8110)
Summary:
Fixes #7867 [test_vlan_ping] [ test issue ] | 'str' object has no attribute 'decode'

What is the motivation for this PR?
Test failed after Python3 migration.
vm_ip_with_prefix = (vm_info['conf']['interfaces']['Port-Channel1']['ipv4']).decode('utf-8')
E AttributeError: 'str' object has no attribute 'decode'

How did you do it?
Use six.ensure_text. In Python2, ensure_text returns unicode and returns str in Python3.
In Python3, there is no need to use decode()

How did you verify/test it?
Manually run the test case.