Fix the snmp bug: #3355826:
This issue is introduced by the merge from upstream, we need to update the pdu info in the lab_connection_graph file
[SONiC – Verification] Bug SW #3355826: [Functional ] [psu] | platform_info_test_turn_on_off_psu_and_check_psustatus failed with AttributeError: snmpPduController instance has no attribute 'PORT_NAME_BASE_OID' | Assignee: Nana He | Status: In Progress

Change-Id: I1bb154027014dda5ebcde0e2a5091b677373e8b5