local fix for sensor test issue from community
In community PR (https://github.com/Azure/sonic-mgmt/pull/4612) was added python3 support to sensor test - decote to output and error msgs.
The change was not correct and when(lot of time) the no error msg exists - the test failed with error: "'NoneType' object has no attribute 'decode'"


Change-Id: I29bc26b999a8c05636b8dea67c3e23e921c7abcb
Signed-off-by: Anton <antonh@nvidia.com>