Fixed TypeError: deploy_image() got an unexpected keyword argument 'platform'
Few days ago we did some changes in deploy script, but not all code were modified, this fix fixes missed part of code

Change-Id: Iec5bb4ea2707a278e4970f02819286998d8cab68